# change to list chars of your dataset or use default vietnamese chars
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '

# cpu, cuda, cuda:0
device: cuda:0

image_encoder:
    hidden_dim: 512
    pretrained: True
    drop_out: 0.1
seq_modeling: seq2seq
transformer:
    encoder_hidden: 512
    decoder_hidden: 512
    img_channel: 512
    decoder_embedded: 512
    dropout: 0.15

optimizer:
    max_lr: 0.001
    pct_start: 0.1

trainer:
    batch_size: 32
    print_every: 1
    valid_every: 5
    checkpoint_every: 20
    iters: 100
    # where to save our model for prediction
    export: /content/mocr/weights/transformerocr.pth
    checkpoint: /content/mocr/checkpoint/transformerocr_checkpoint.pth
    log: ./train.log
    # null to disable compuate accuracy, or change to number of sample to enable validiation while training
    metrics: null

dataset:    
    # name of your dataset
    name: data
    # path to annotation and image
    data_root: /content/vn_handwritten_images/data/
    train_annotation: /content/vn_handwritten_images/labels.json
    valid_annotation: null
    image_height: 128
    image_min_width: 32
    image_max_width: 512

dataloader:
    num_workers: 2
    pin_memory: True

aug:
    image_aug: True
    masked_language_model: True

predictor:
    # disable or enable beamsearch while prediction, use beamsearch will be slower
    beamsearch: False
    weights: /content/mocr/weights/transformerocr.pth
quiet: False 
split: True